### ISSUE TITLE
Error android 6.0.1 on nexus 5

### ISSUE THREAD

**Issue by dovanvu1792** [DevLight-Mobile-Agency/NavigationTabBar#23]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.gigamole.navigationtabbar/com.gigamole.navigationtabbar.MainActivity}: **java.lang.ClassNotFoundException: Didn't find class "com.gigamole.navigationtabbar.MainActivity"** on path: DexPathList[[zip file "/data/app/com.gigamole.navigationtabbar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gigamole.navigationtabbar-1/lib/arm, /vendor/lib, /system/lib]]
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.gigamole.navigationtabbar.MainActivity" on path: DexPathList[[zip file "/data/app/com.gigamole.navigationtabbar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gigamole.navigationtabbar-1/lib/arm, /vendor/lib, /system/lib]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               	**Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.gigamole.navigationtabbar.MainActivity"** on path: DexPathList[[dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-support-annotations-23.4.0_e29451ecbafa43ab8360f08f2358b7f7ded12169-classes.dex", dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-internal_impl-23.4.0_ed6077c7ae36854a156f5057e37ddfc5539f0265-classes.dex", dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.4.0_590f3995813849c4d48fcd3942188e26f8f68645-classes.dex", dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-com.android.support-support-v4-23.4.0_f0ff20939018b86d3213b795982102f39afece23-classes.dex", dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.4.0_90472ccc4c6fbfca7e6511b836cd08a98fd2e4cb-classes.dex", dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-com.android.support-design-23.4.0_ab15a4269ad22fa06be63b7923f8a4cfcce35a2f-classes.dex", dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.4.0_8bda3a59524d420ce46af580679524efcc621bf5-classes.dex", dex file "/data/data/com.gigamole.navigationtabbar/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.4.0_fc68d0f0347c6fa313857b324630255d52caed51-classes.dex"],nativeLibraryDirectories=[/data/app/com.gigamole.navigationtabbar-1/lib/arm, /vendor/lib, /system/lib]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                                                   at com.android.tools.fd.runtime.IncrementalClassLoader.findClass(IncrementalClassLoader.java:62)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                   		... 12 more
                                                                               		Suppressed: **java.lang.ClassNotFoundException: com.gigamole.navigationtabbar.MainActivity
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at** java.lang.BootClassLoader.findClass(ClassLoader.java:781)

**Comment by GIGAMOLE** [comment]
Hello. Thanks for feedback. It looks like problem in sample.

**Comment by GIGAMOLE** [comment]
Try to clean project and reinstall app. This problem is individual.
