### ISSUE TITLE
null object reference

### ISSUE THREAD

**Issue by MrThiago** [DevLight-Mobile-Agency/NavigationTabBar#32]
When I try to run my code I get this.

I included you library from code

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue. What version do you use and do you use compile dependency link? It seems not possible, cause my library never call recycle() bitmap. Maybe you call some methods like.

**Comment by MrThiago** [comment]
using 

compile 'com.github.devlight.navigationtabbar:navigationtabbar:1.2.3'

**Comment by GIGAMOLE** [comment]
What phone do you use?

**Comment by MrThiago** [comment]
Lenovo tab 3, If I run you sample app from github, it works fine. 
I only the get error when I import your library into my project

**Comment by MrThiago** [comment]
fulll error:


E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.rokki.life3, PID: 8797
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
                                                                   at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1281)
                                                                   at android.graphics.Canvas.drawBitmap(Canvas.java:1337)
                                                                   at com.gigamole.navigationtabbar.ntb.NavigationTabBar.onDraw(NavigationTabBar.java:1091)
                                                                   at android.view.View.draw(View.java:15242)
                                                                   at android.view.View.buildDrawingCacheImpl(View.java:14488)
                                                                   at android.view.View.buildDrawingCache(View.java:14350)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14159)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.View.draw(View.java:14970)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.View.draw(View.java:14970)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                   at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1131)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                   at android.view.View.draw(View.java:15245)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14178)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.View.draw(View.java:14970)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.View.draw(View.java:14970)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.View.draw(View.java:14970)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.View.draw(View.java:14970)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.View.draw(View.java:14970)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                   at android.view.View.draw(View.java:15245)
                                                                   at android.widget.FrameLayout.draw(FrameLayout.java:599)
                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2673)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:14178)
                                                                   at android.view.View.getDisplayList(View.java:14200)
                                                                   at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                                                                   at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                                                                   at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                                                                   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2548)
                                                                   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2364)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1994)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5903)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:586)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:556)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                               	at android.app.ActivityThread.main(ActivityThread.java:5254

**Comment by GIGAMOLE** [comment]
Try to look at your icon resources. Maybe there some kind of issue.

**Comment by MrThiago** [comment]
just the basic:

final String[] colors = getResources().getStringArray(R.array.vertical_ntb);
        final NavigationTabBar navigationTabBar = (NavigationTabBar) findViewById(R.id.ntb);
        final ArrayList<NavigationTabBar.Model> models = new ArrayList<>();
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.close_icon),
                        Color.parseColor(colors[0])
                ).title("Heart")
                        .badgeTitle("NTB")
                        .build()
        );

**Comment by GIGAMOLE** [comment]
Only one element?

**Comment by MrThiago** [comment]
its crashing at the inflating the XML,

**Comment by GIGAMOLE** [comment]
I dont know. This is inetersting.

**Comment by MrThiago** [comment]
check this out:
does it have anything to do with the fonts: ?


java.lang.RuntimeException: Font asset not found fonts/custom_typeface.ttf
07-04 16:40:19.103 31631-31631/my.app W/System.err:     at android.graphics.Typeface.createFromAsset(Typeface.java:190)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at com.gigamole.navigationtabbar.ntb.NavigationTabBar.setTypeface(NavigationTabBar.java:605)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at com.gigamole.navigationtabbar.ntb.NavigationTabBar.<init>(NavigationTabBar.java:349)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at com.gigamole.navigationtabbar.ntb.NavigationTabBar.<init>(NavigationTabBar.java:296)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
07-04 16:40:19.104 31631-31631/my.app W/System.err:     at my.app.views.ui.home.MainActivity.onCreate(MainActivity.java:26)

**Comment by GIGAMOLE** [comment]
Yes. This is error, cause there are no fonts/custom_typeface.ttf. This is sample feature highlight. Just remove this line from XML.

**Comment by MrThiago** [comment]
still getting error 

<com.gigamole.navigationtabbar.ntb.NavigationTabBar
        android:id="@+id/ntb"
        android:layout_width="match_parent"
        android:layout_height="50dp"/>



FATAL EXCEPTION: main
                                                                 Process: com.rokki.life3, PID: 12376
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
                                                                     at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1281)
                                                                     at android.graphics.Canvas.drawBitmap(Canvas.java:1337)
                                                                     at com.gigamole.navigationtabbar.ntb.NavigationTabBar.onDraw(NavigationTabBar.java:1091)
                                                                     at android.view.View.draw(View.java:15242)
                                                                     at android.view.View.buildDrawingCacheImpl(View.java:14488)
                                                                     at android.view.View.buildDrawingCache(View.java:14350)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14159)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.View.draw(View.java:14970)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.View.draw(View.java:14970)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1131)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.draw(View.java:15245)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14178)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.View.draw(View.java:14970)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.View.draw(View.java:14970)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.View.draw(View.java:14970)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.View.draw(View.java:14970)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14173)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.View.draw(View.java:14970)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                     at android.view.View.draw(View.java:15245)
                                                                     at android.widget.FrameLayout.draw(FrameLayout.java:599)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2673)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14178)
                                                                     at android.view.View.getDisplayList(View.java:14200)
                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2548)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2364)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1994)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5903)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:586)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:556)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                 	at android.app.ActivityThread.main(ActivityThread.java:525

**Comment by GIGAMOLE** [comment]
You icon is vector?

**Comment by GIGAMOLE** [comment]
Its seems like your icon is incorrect. Can you give more info about it.
