### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by triasbrata** [DevLight-Mobile-Agency/NavigationTabBar#37]
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
                                                                               at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1281)
                                                                               at android.graphics.Canvas.drawBitmap(Canvas.java:1337)
                                                                               at com.gigamole.navigationtabbar.ntb.NavigationTabBar.onDraw(NavigationTabBar.java:1091)`

I do not understand why the random error could happen when I use the Fragment on ViewPager. and I use Bitmap that I have downloaded the library ImageRequest of Volley then converted to a Drawable, sometimes can sometimes error as above, even when I replace the existing image on fixed Drawable error sometimes occurs and sometimes succeed

**Comment by GIGAMOLE** [comment]
Hello. Thanks for bug report. This crash cause of low memory. Try to optimize your app cause my NTB need much resource to draw it. In new update i wiil try fix up, where it could get this crash. Thanks.

**Comment by GIGAMOLE** [comment]
Update 1.2.4 is on the rails. Thanks.
