### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference

### ISSUE THREAD

**Issue by zengcanxiang** [DevLight-Mobile-Agency/NavigationTabBar#51]
I put the layout file inside the TopHorizontalNtbActivity class AppBarLayout that copy out, and then on the wrong.
but ,I don't have the control.Is it because of this？

```java
  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
                                                                          at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1269)
                                                                          at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
                                                                          at com.gigamole.navigationtabbar.ntb.NavigationTabBar.onDraw(NavigationTabBar.java:1091)
                                                                          at android.view.View.draw(View.java:16178)
                                                                          at android.view.View.buildDrawingCacheImpl(View.java:15474)
                                                                          at android.view.View.buildDrawingCache(View.java:15335)
                                                                          at android.view.View.draw(View.java:15941)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                          at android.view.View.draw(View.java:15948)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.draw(View.java:16181)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                          at android.view.View.draw(View.java:15948)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.draw(View.java:16181)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                          at android.view.View.draw(View.java:15948)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                          at android.view.View.draw(View.java:15948)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                          at android.view.View.draw(View.java:15948)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                          at android.view.View.draw(View.java:15948)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                          at android.view.View.draw(View.java:15948)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                          at android.view.View.draw(View.java:16181)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by GIGAMOLE** [comment]
Hello. Thanks for this issue. New version have fixed up this error.
