### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0 navigation tab bar

### ISSUE THREAD

**Issue by Beckuro** [DevLight-Mobile-Agency/NavigationTabBar#67]
i just got 
java.lang.IllegalArgumentException: width and height must be > 0 navigation tab bar

**Comment by Beckuro** [comment]
sorry it was all my fault

**Comment by ashishoc** [comment]
I'm facing  same

**Comment by fashioncj** [comment]
` java.lang.IllegalArgumentException: width and height must be > 0
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
                                                                               at devlight.io.library.ntb.NavigationTabBar.onDraw(NavigationTabBar.java:1077)
                                                                               at android.view.View.draw(View.java:17189)
                                                                               at android.view.View.buildDrawingCacheImpl(View.java:16478)
                                                                               at android.view.View.buildDrawingCache(View.java:16339)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16152)
                                                                               at android.view.View.draw(View.java:16955)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                               at android.view.View.draw(View.java:16955)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                               at android.view.View.draw(View.java:16955)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                               at android.view.View.draw(View.java:16955)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                               at android.view.View.draw(View.java:16955)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16166)
                                                                               at android.view.View.draw(View.java:16955)
                                                                               at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                               at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                               at android.view.View.draw(View.java:17192)
                                                                               at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16171)
                                                                               at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                               at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                               at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                               at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                               at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by lorduriel** [comment]
@Beckuro What was your issue and how did you solve it?
I can´t solve it

**Comment by mcauto** [comment]
I'm facing same please help

**Comment by mdtuyen** [comment]
You need setup models first before onDraw called.

**Comment by kvaruna** [comment]
@mdtuyen What do you suggest exactly? 
Can you share any code snippet?

**Comment by kvaruna** [comment]
> sorry it was all my fault
Hi, 

What was your fault? May be am doing the same thing.

**Comment by mcauto** [comment]
@kvaruna 
you should use butterknife binding first.
